server:
  servlet:
    context-path: /lenrn

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/lenrn?characterEncoding=utf-8&useSSL=false
  servlet:
    multipart:
      max-file-size: 10MB
  http:
    multipart:

  session:
    store-type: redis
  redis:
    database: 0
    host: localhost
    port: 6379



